import { TrackDefinition } from './types';
import { EXPLANATION_REVIEW_BLOCK, MEDIA_SITUATION_CUSTOM, MEDIA_SITUATION_TEXT } from './shared';

export const TRACK_TWO_DAY_V1: TrackDefinition = {
  id: 's2',
  version: 's2-v1',
  code: '2-Day track',
  duration: '2',
  durationUnit: 'DAYS',
  title: '2-Day Practical Hiring Task',
  subtitle: 'Easy version',
  workingTime: '9:00 AM – 6:30 PM, both days',
  cardDesc:
    'A deeper, two-day version: own a small game-development module end to end — research, module, prototype, media handoff, QA and a release decision.',
  overview: {
    role: [
      'You are the Game Development Technical POC.',
      'Understand the idea given by the G Engineer team.',
      'Research the game-development topic.',
      'Create the syllabus and lesson sequence.',
      'Build and test the Unity demo.',
      'Prepare the teaching content.',
      'Guide the media/production team.',
      'Check technical correctness during recording and editing.',
      'Handle problems and keep the work moving.',
      'Decide whether the content is ready to release.',
    ],
    scenarioText:
      'G Engineer is restarting its game-development content. You are responsible for preparing one small module that could actually enter our future production process. Unity will be used for the practical work.',
    callouts: [
      {
        title: 'Why we give this task',
        text: 'This is a deeper version of the 1-day task. We want to see whether you can own a small game-development content module from start to finish: research → syllabus → Unity project → lesson → media handoff → technical review → final release decision.',
      },
      {
        title: 'What we are NOT testing',
        text: 'We are not expecting a huge game or final-quality art. We are testing your technical ability, planning, teaching, documentation, coordination and ownership.',
      },
    ],
  },
  schedule: [
    { day: 'Day 1', time: '9:00–9:20', todo: 'Understand + plan', give: 'Questions, scope, success criteria', check: 'Planning' },
    { day: 'Day 1', time: '9:20–10:45', todo: 'Research', give: 'Research document', check: 'Technical research' },
    { day: 'Day 1', time: '10:45–12:15', todo: 'Create module plan', give: '5–8 lesson roadmap', check: 'Curriculum thinking' },
    { day: 'Day 1', time: '12:15–1:00', todo: 'Plan the technical demo', give: 'Architecture + project plan', check: 'Engineering thinking' },
    { day: 'Day 1', time: '1:00–1:45', todo: 'Break', give: '—', check: '—' },
    { day: 'Day 1', time: '1:45–4:15', todo: 'Build the Unity prototype', give: 'Working prototype', check: 'Unity + C#' },
    { day: 'Day 1', time: '4:15–5:00', todo: 'Test + debug', give: 'Bug/test list', check: 'QA' },
    { day: 'Day 1', time: '5:00–6:00', todo: 'Prepare one lesson', give: 'Lesson draft', check: 'Teaching' },
    { day: 'Day 1', time: '6:00–6:30', todo: 'Day 1 review', give: 'Demo + Day 2 plan', check: 'Progress + scope' },
    { day: 'Day 2', time: '9:00–9:20', todo: 'Review Day 1', give: 'Updated plan', check: 'Adaptability' },
    { day: 'Day 2', time: '9:20–11:00', todo: 'Finish + improve demo', give: 'Stable, cleaner demo', check: 'Engineering quality' },
    { day: 'Day 2', time: '11:00–12:00', todo: 'Create learner challenge', give: 'Requirements + rubric', check: 'Project-based learning' },
    { day: 'Day 2', time: '12:00–1:00', todo: 'Prepare production brief', give: 'Script + recording plan', check: 'Media coordination' },
    { day: 'Day 2', time: '1:00–1:45', todo: 'Break', give: '—', check: '—' },
    { day: 'Day 2', time: '1:45–2:45', todo: 'POC problem simulation', give: 'Issue handling + tracker', check: 'Ownership' },
    { day: 'Day 2', time: '2:45–3:45', todo: 'Technical QA', give: 'Final QA checklist', check: 'Release quality' },
    { day: 'Day 2', time: '3:45–4:30', todo: 'Create simple SOP', give: 'One-page process', check: 'Systems thinking' },
    { day: 'Day 2', time: '4:30–5:15', todo: 'Final package', give: 'All files organized', check: 'Completeness' },
    { day: 'Day 2', time: '5:15–6:30', todo: 'Final presentation', give: 'Presentation + Q&A', check: 'Judgment + communication' },
  ],
  sections: [
    {
      id: 's2-d1r', kind: 'qa', label: 'Day 1', title: 'Research',
      fields: [
        { id: 'topic', label: 'What is the topic?', type: 'text' },
        { id: 'learner', label: 'Who is the learner?', type: 'textarea' },
        { id: 'why', label: 'Why is it important?', type: 'textarea' },
        { id: 'prereq', label: 'What should the learner know first?', type: 'textarea' },
        { id: 'usage', label: 'How is it used in real games?', type: 'textarea' },
        { id: 'mistakes', label: 'What are 5 common mistakes?', type: 'textarea' },
        { id: 'debug', label: 'How would you debug those mistakes?', type: 'textarea' },
        { id: 'risk', label: 'What can go wrong technically?', type: 'textarea' },
        { id: 'challenge', label: 'What small challenge can the learner build?', type: 'textarea' },
        { id: 'challengeLink', label: 'Challenge / assignment link', type: 'url', hint: 'If your challenge uses a document, video, GitHub repository, reference project, or other resource, paste the link here.' },
      ],
      extra: [
        { type: 'linklist', id: 'sources', heading: 'Sources', addLabel: '+ Add source', titleLabel: 'Source name / title', noteLabel: 'What did you use this source for?', emptyText: 'No sources added yet — add each source you used below.', sub: 'Add every source you used: documentation, articles, videos, PPTs, PDFs, GitHub repos, or anything else.' },
      ],
    },
    {
      id: 's2-d1m', kind: 'repeatable', label: 'Day 1', title: 'Create the module', minRows: 5,
      tip: 'Main question: if a beginner follows these lessons, will they actually become better at building games — or are they only watching Unity features?',
      note: ['Create 5–8 connected lessons.'],
      columns: [
        { id: 'objective', label: 'Lesson objective', type: 'text' },
        { id: 'explained', label: 'What is explained', type: 'textarea' },
        { id: 'demonstrated', label: 'What is demonstrated', type: 'textarea' },
        { id: 'challenge', label: 'Small challenge', type: 'textarea' },
        { id: 'assignment', label: 'Assignment', type: 'textarea' },
        { id: 'assignmentLink', label: 'Assignment / reference link', type: 'url' },
        { id: 'mistakes', label: 'Common mistakes', type: 'textarea' },
        { id: 'interview', label: 'Interview questions', type: 'textarea' },
        { id: 'resources', label: 'Resources', type: 'textarea' },
        { id: 'resourcesLink', label: 'Resource link', type: 'url' },
        { id: 'recap', label: 'Recap', type: 'textarea' },
        { id: 'next', label: 'Next lesson', type: 'text' },
      ],
    },
    {
      id: 's2-d1p', kind: 'qa', label: 'Day 1', title: 'Build the Unity prototype',
      note: ['Use C# properly where needed.', 'Keep scripts and folders organized.', 'Test while building.'],
      fields: [
        { id: 'arch', label: 'Why did you design the system this way?', type: 'textarea' },
        { id: 'bugs', label: 'Bugs you found, and how you fixed them', type: 'textarea' },
        { id: 'filesLink', label: 'Prototype files / additional resources', type: 'url' },
      ],
      extra: [
        { type: 'linklist', id: 'links', heading: 'Prototype / project links', addLabel: '+ Add link', titleLabel: 'Link title', noteLabel: 'Short description', emptyText: 'No links added yet — this is how the evaluator opens your work.', sub: 'Unity project/repository, GitHub, a playable build, a screen recording, or another reference.' },
      ],
    },
    {
      id: 's2-d1l', kind: 'qa', label: 'Day 1', title: 'Prepare one full lesson',
      fields: [
        { id: 'result', label: 'Show the final result', type: 'textarea' },
        { id: 'why', label: 'Why it matters', type: 'textarea' },
        { id: 'concept', label: 'Explain the concept', type: 'textarea' },
        { id: 'steps', label: 'Build/show it step by step', type: 'textarea' },
        { id: 'stepsLink', label: 'Demo / reference link', type: 'url' },
        { id: 'challenge', label: 'Give a challenge', type: 'textarea' },
        { id: 'challengeLink', label: 'Challenge link', type: 'url' },
        { id: 'solution', label: 'Explain the solution', type: 'textarea' },
        { id: 'solutionLink', label: 'Solution / reference link', type: 'url' },
        { id: 'assignment', label: 'Give an assignment', type: 'textarea' },
        { id: 'assignmentLink', label: 'Assignment link', type: 'url' },
        { id: 'mistakes', label: 'Explain common mistakes', type: 'textarea' },
        { id: 'recap', label: 'Recap and show what comes next', type: 'textarea' },
      ],
      extra: [
        { type: 'linklist', id: 'resources', heading: 'Lesson resources', addLabel: '+ Add resource', titleLabel: 'Resource name', noteLabel: 'Optional note', emptyText: 'No resources added yet.', sub: 'Documentation, videos, PDFs, PPTs, GitHub repositories — anything that supports this lesson.' },
      ],
    },
    {
      id: 's2-d2i', kind: 'qa', label: 'Day 2', title: 'Improve the prototype',
      fields: [
        { id: 'finished', label: 'Features you finished (the agreed features)', type: 'textarea' },
        { id: 'cleanup', label: 'Code/project cleanup notes', type: 'textarea' },
        { id: 'freshtest', label: 'Results of testing from a fresh start', type: 'textarea' },
        { id: 'notfinished', label: 'Anything you intentionally did not finish', type: 'textarea' },
      ],
    },
    {
      id: 's2-d2c', kind: 'qa', label: 'Day 2', title: 'Create an industry-style challenge',
      note: ['Give the learner a problem, but do not give them the solution.'],
      fields: [
        { id: 'requirements', label: 'Requirements', type: 'textarea' },
        { id: 'rules', label: 'Rules / constraints', type: 'textarea' },
        { id: 'mustdo', label: 'What the final result must do', type: 'textarea' },
        { id: 'acceptance', label: 'Acceptance criteria', type: 'textarea' },
        { id: 'mistakes', label: 'Common mistakes', type: 'textarea' },
        { id: 'rubric', label: 'Simple scoring rubric', type: 'textarea' },
      ],
    },
    {
      id: 's2-d2b', kind: 'qa', label: 'Day 2', title: 'Media team brief',
      note: ['Prepare a document that the A2D Media Group can use.'],
      fields: [
        { id: 'title', label: 'Video title', type: 'text' },
        { id: 'learner', label: 'Target learner', type: 'text' },
        { id: 'objective', label: 'Learning objective', type: 'textarea' },
        { id: 'presenter', label: 'Presenter instructions', type: 'textarea' },
        { id: 'camera', label: 'Camera shots needed', type: 'textarea' },
        { id: 'screen', label: 'Screen recording needed', type: 'textarea' },
        { id: 'projectstate', label: 'Unity project state needed', type: 'textarea' },
        { id: 'sequence', label: 'Code/demo sequence', type: 'textarea' },
        { id: 'editornotes', label: 'Editor notes', type: 'textarea' },
        { id: 'mustnotchange', label: 'Things the editor must not change', type: 'textarea' },
        { id: 'zooms', label: 'Useful zooms / callouts', type: 'textarea' },
        { id: 'assignment', label: 'Assignment at the end', type: 'textarea' },
        { id: 'checklist', label: 'Final technical checklist', type: 'textarea' },
      ],
      extra: [
        { type: 'linklist', id: 'mediarefs', heading: 'Media / reference materials', addLabel: '+ Add reference', titleLabel: 'Name', noteLabel: 'What should the media person use this for?', emptyText: 'No reference materials added yet.', sub: 'Reference document/PPT, script or lesson document, Unity project, demo link, screen-recording reference, assets/files, or other material.' },
        EXPLANATION_REVIEW_BLOCK,
      ],
    },
    {
      id: 's2-d2p', kind: 'situations', label: 'Day 2', title: 'POC problem situations',
      items: [
        { id: 'sit0', text: 'Editor changed something and the technical meaning became wrong.' },
        { id: 'sit1', text: 'A bug is found just before the deadline.' },
        { id: 'sit2', text: 'Wrong Unity project/version was recorded.' },
        { id: 'sit3', text: 'A required asset is missing.' },
        { id: 'sit4', text: 'Two videos need your review at the same time.' },
        { id: 'sit5', text: 'A production team member disagrees with your technical correction.' },
        { id: 'sitmedia', text: MEDIA_SITUATION_TEXT, custom: MEDIA_SITUATION_CUSTOM },
      ],
    },
    {
      id: 's2-d2qa', kind: 'checklist', label: 'Day 2', title: 'Technical QA',
      decisionLabel: 'Final decision', decisionOptions: ['RELEASE', 'REVISE', 'BLOCK'],
      items: [
        'Does the lesson achieve its learning goal?', 'Does the Unity demo work from a clean start?',
        'Is the technical explanation correct?', 'Is the code correct and understandable?',
        'Is the screen recording readable?', 'Is the assignment clear?',
        'Are project files/resources available?', 'Did editing introduce any technical mistake?',
        'Can another person reproduce the demo?',
      ],
    },
    {
      id: 's2-sop', kind: 'qa', label: 'Day 2', title: 'Simple SOP',
      note: ['Write one page called "Game Development Video — Technical Handoff & QA".'],
      fields: [
        { id: 'gives', label: 'What the education team gives you', type: 'textarea' },
        { id: 'prepare', label: 'What you prepare', type: 'textarea' },
        { id: 'test', label: 'How you test the demo', type: 'textarea' },
        { id: 'handoff', label: 'How you hand it to the media team', type: 'textarea' },
        { id: 'recordingcheck', label: 'How recording is checked', type: 'textarea' },
        { id: 'editreview', label: 'How editing is technically reviewed', type: 'textarea' },
        { id: 'approval', label: 'How final approval happens', type: 'textarea' },
      ],
    },
    {
      id: 's2-sub', kind: 'checklist', label: 'Submit', title: 'Final submission',
      items: [
        'Research document', '5–8 lesson module', 'Working Unity project', 'Technical plan', 'Bug/test notes',
        'One complete lesson', 'Learner challenge + rubric', 'Production/media brief', 'Issue/production tracker',
        'Technical QA checklist', 'Simple SOP', 'Final presentation',
      ],
    },
  ],
  scoring: {
    areas: [
      { id: 'research', label: 'Research', check: 'Technical understanding + good research', max: 10 },
      { id: 'curriculum', label: 'Curriculum', check: 'Good learning sequence + clear outcomes', max: 15 },
      { id: 'unity', label: 'Unity / C#', check: 'Working project + code + debugging', max: 20 },
      { id: 'teaching', label: 'Teaching', check: 'Clear and practical explanation', max: 10 },
      { id: 'production', label: 'Production', check: 'Good media-team brief', max: 10 },
      { id: 'poc', label: 'POC Ownership', check: 'Problem solving + coordination', max: 15 },
      { id: 'qa', label: 'QA', check: 'Testing + release decision', max: 10 },
      { id: 'documentation', label: 'Documentation', check: 'Clear and reusable documents', max: 5 },
      { id: 'presentation', label: 'Final Presentation', check: 'Communication + judgment', max: 5 },
    ],
  },
};
